apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amf
  labels:
    5g: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: amf
  template:
    metadata:
      labels:
        5g: amf
    spec:
      containers:
        - name: amf
          image: amf:latest
          imagePullPolicy: Never
          env:
            - name: AMF_ADDR
              value: 0.0.0.0
            - name: NGAP_ADDR
              value: 0.0.0.0
            - name: METRICS_ADDR
              value:
            - name: METRICS_PORT
              value:
            - name: MCC
              value:
            - name: MNC
              value:
            - name: NETWORK_NAME
              value:
---
apiVersion: v1
kind: Service
metadata:
  name: amf-service
spec:
  type: ClusterIP
  selector:
    5g: amf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: amf-node-service
spec:
  type: NodePort
  selector:
    5g: amf
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
      nodePort: 32412
