apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  labels:
    5g: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: amf
  template:
    metadata:
      labels:
        5g: amf
    spec:
      containers:
        - name: amf
          image: amf:latest
          imagePullPolicy: Never
          env:
            - name: MCC
              value: "001"
            - name: MNC
              value: "01"
            - name: NETWORK_NAME
              value:
            - name: SCP_ADDR
              value: scp-service
            - name: NRF_ADDR
              value: nrf-service
          command: ["sh"]
          args: ["-c", "export AMF_ADDR=`ip a show eth0 | grep inet | sed 's/ *//' | cut -d' ' -f2 | cut -d'/' -f1` && export NGAP_ADDR=$AMF_ADDR && /root/setup.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: amf-service
spec:
  type: ClusterIP
  selector:
    5g: amf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: amf-node-service
spec:
  type: NodePort
  selector:
    5g: amf
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
      nodePort: 38412
