apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsf
  labels:
    5g: bsf
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: bsf
  template:
    metadata:
      labels:
        5g: bsf
    spec:
      containers:
        - name: bsf
          image: bsf:latest
          imagePullPolicy: Always
          env:
            - name: DB_URI
              value: mongodb://mongo-service/open5gs
            - name: SCP_ADDR
              value: scp-service
            - name: NRF_ADDR
              value: nrf-service
            - name: LOG_ADDR
              value: "192.168.39.1" # logger server address
            - name: LOG_PORT
              value: "1514"
          command: ["sh"]
          args: ["-c", "export BSF_ADDR=`ip a show eth0 | grep \"inet[^6]\" | sed 's/ *//' | cut -d' ' -f2 | cut -d'/' -f1` && /root/setup.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: bsf-service
spec:
  type: ClusterIP
  selector:
    5g: bsf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
