apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo
  clusterIP: 10.96.1.10
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
