apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  labels:
    5g: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: pcf
  template:
    metadata:
      labels:
        5g: pcf
    spec:
      containers:
        - name: pcf
          image: pcf:latest
          imagePullPolicy: Never
          env:
            - name: DB_URI
              value: mongodb://mongo-service/open5gs
            - name: SCP_ADDR
              value: scp-service
            - name: NRF_ADDR
              value: nrf-service
            - name: LOG_ADDR
              value: "192.168.39.1" # logger server address
            - name: LOG_PORT
              value: "1514"
          command: ["sh"]
          args: ["-c", "export PCF_ADDR=`ip a show eth0 | grep inet | sed 's/ *//' | cut -d' ' -f2 | cut -d'/' -f1` && /root/setup.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: pcf-service
spec:
  type: ClusterIP
  selector:
    5g: pcf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
