apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.39.1
    path: /srv/nfs/mongo
  storageClassName: "mongo"
