apiVersion: apps/v1
kind: Deployment
metadata:
  name: scp
  labels:
    5g: scp
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: scp
  template:
    metadata:
      labels:
        5g: scp
    spec:
      containers:
        - name: scp
          image: scp:latest
          imagePullPolicy: Never
          env:
            - name: DB_URI
              value: mongodb://mongo-service/open5gs
            - name: NRF_ADDR
              value: nrf-service
          command: ["sh"]
          args: ["-c", "export SCP_ADDR=`ip a show eth0 | grep inet | sed 's/ *//' | cut -d' ' -f2 | cut -d'/' -f1` && /root/setup.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: scp-service
spec:
  type: ClusterIP
  selector:
    5g: scp
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
