apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  labels:
    5g: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: smf
  template:
    metadata:
      labels:
        5g: smf
    spec:
      containers:
        - name: smf
          image: smf:latest
          imagePullPolicy: Never
          env:
            - name: SMF_ADDR
              value: 0.0.0.0
            - name: PFCP_ADDR
              value: 0.0.0.0
            - name: GTPC_ADDR
              value: 0.0.0.0
            - name: GTPU_ADDR
              value: 0.0.0.0
            - name: DNS_ADDR
              value:
            - name: SCP_ADDR
              value: scp-service
            - name: UPF_ADDR
              value: upf-service
            - name: NRF_ADDR
              value: nrf-service
---
apiVersion: v1
kind: Service
metadata:
  name: smf-service
spec:
  type: ClusterIP
  selector:
    5g: smf
  ports:
    - protocol: UDP
      port: 2123
      targetPort: 2123
      name: gtpc
    - protocol: UDP
      port: 2152
      targetPort: 2152
      name: gtpu
    - protocol: UDP
      port: 8805
      targetPort: 8805
      name: pfcp
    - protocol: TCP
      port: 7777
      targetPort: 7777
      name: sbi
