apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  labels:
    5g: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: udm
  template:
    metadata:
      labels:
        5g: udm
    spec:
      containers:
        - name: udm
          image: udm:latest
          imagePullPolicy: Never
          env:
            - name: SCP_ADDR
              value: scp-service
            - name: NRF_ADDR
              value: nrf-service
          command: ["sh"]
          args: ["-c", "export UDM_ADDR=`ip a show eth0 | grep inet | sed 's/ *//' | cut -d' ' -f2 | cut -d'/' -f1` && /root/setup.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: udm-service
spec:
  type: ClusterIP
  selector:
    5g: udm
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
