apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  labels:
    5g: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: udm
  template:
    metadata:
      labels:
        5g: udm
    spec:
      containers:
        - name: udm
          image: 192.168.39.1:5000/udm:latest
          imagePullPolicy: Always
          env:
            - name: SCP_ADDR
              value: scp-service
            - name: NRF_ADDR
              value: nrf-service
            - name: LOG_ADDR
              value: "192.168.39.1" # logger server address
            - name: LOG_PORT
              value: "1514"
          command: ["sh"]
          args: ["-c", "export UDM_ADDR=`ip a show eth0 | grep \"inet[^6]\" | sed 's/ *//' | cut -d' ' -f2 | cut -d'/' -f1` && /root/setup.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: udm-service
spec:
  type: ClusterIP
  selector:
    5g: udm
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
