apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  labels:
    5g: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: udr
  template:
    metadata:
      labels:
        5g: udr
    spec:
      containers:
        - name: udr
          image: udr:latest
          imagePullPolicy: Never
          env:
            - name: DB_URI
              value: mongodb://mongo-service/open5gs
            - name: SCP_ADDR
              value: scp-service
            - name: NRF_ADDR
              value: nrf-service
          command: ["sh"]
          args: ["-c", "export UDR_ADDR=`ip a show eth0 | grep inet | sed 's/ *//' | cut -d' ' -f2 | cut -d'/' -f1` && /root/setup.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: udr-service
spec:
  type: ClusterIP
  selector:
    5g: udr
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
