apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  labels:
    5g: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      5g: webui
  template:
    metadata:
      labels:
        5g: webui
    spec:
      containers:
        - name: webui
          image: 192.168.39.1:5000/webui:latest
          imagePullPolicy: Always
          env:
          - name: DB_URI
            value: mongodb://mongo-service/open5gs
---
apiVersion: v1
kind: Service
metadata:
  name: webui-node-service
spec:
  type: NodePort
  selector:
    5g: webui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32500
